### ISSUE TITLE
How can i update ?

### ISSUE THREAD

**Issue by vBDSK** [laam4/noxus#12]
You made fix for noxus hlstatsx and i want to update.
How can i make update?
Can you make guide for update ?
ty.

**Comment by melkor217** [comment]
Well, the process itself probably should look like
- ALTER TABLE hlstats_Players ADD mmrank TINYINT AFTER icq;
- Replace php files
- Replace perl daemon files
- If you use superlogs-csgo plugin, you should also compile it and put to servers

**Comment by vBDSK** [comment]
melkor217, thank you

**Comment by vBDSK** [comment]
melkor217, ты написал процесс обновления со старой версии noxus'а до новой с фиксами?
Или с обычной hlstatsx до noxus'а?

**Comment by laam4** [comment]
I understood that you have fixed something and want to share your fix? You have to fork this repository, make your changes to your forked repository and then make pull request to this repository.

**Comment by melkor217** [comment]
@vBDSK, update process is always the same, with an exception for the first item. You have to run SQL only if you have database from vanilla hlstatsx

@laam4 Naah, he just wanna upgrade noxus to the latest version
