### ISSUE TITLE
Unwanted quotes in player names

### ISSUE THREAD

**Issue by melkor217** [laam4/noxus#13]
http://noxus.lakuz.com/hlstats.php?mode=search&game=retake&st=player&q=%22

Most likely that issue is related to superlogs or daemon parser

**Comment by melkor217** [comment]
http://noxus.lakuz.com/hlstats.php?mode=playerinfo&player=22496 this, for example. Steam profile name does not contain that double qoute.

**Comment by laam4** [comment]
This happens if someone is assigned to spectator team. Something to do with the clantag function in the daemon.

**Comment by laam4** [comment]
https://github.com/laam4/noxus/blob/master/hlxce/scripts/hlstats.pl#L2749 I guess the error is here

**Comment by laam4** [comment]
`} elsif ($s_output =~ /^"(.+?(?:<.+?>)*?)" triggered "clantag" \(value "(.+?)?"\)$/) {
`
I guess it should be like this?

**Comment by melkor217** [comment]
Yea, that's it most likely. Thanks.
