### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by vBDSK** [laam4/noxus#18]
L 07/25/2016 - 00:34:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 07/25/2016 - 00:34:33: [SM] Blaming: hlstatsx/elorank.smx()
L 07/25/2016 - 00:34:33: [SM] Call stack trace:
L 07/25/2016 - 00:34:33: [SM]   [0] SQL_FastQuery
L 07/25/2016 - 00:34:33: [SM]   [1] Line 73, C:\Users\vbdsk\Desktop\scripting_173\elorank.sp::EloHandler()
L 07/25/2016 - 00:34:36: Error log file session closed.

Fix please

**Comment by laam4** [comment]
Check my answer on Issue #1 
TODO: add documentation for this

**Comment by vBDSK** [comment]
laam4, can you remake plugin elorank databases.cfg like
"elorank"
        {
                "driver"                        "mysql"
                "host"                          "hlstatsIP"
                "database"                      "hlstatsx"
                "user"                          "hlxuser"
                "pass"                          "password"
        }

**Comment by laam4** [comment]
That was also on my TODO list , I'll try to update it this weekend. :+1:

**Comment by melkor217** [comment]
Please do it, or i'll report u otherwise.
