### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by vBDSK** [laam4/noxus#19]
L 08/12/2016 - 05:56:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 08/12/2016 - 05:56:40: [SM] Blaming: hlstatsx/elorank.smx()
L 08/12/2016 - 05:56:40: [SM] Call stack trace:
L 08/12/2016 - 05:56:40: [SM]   [0] SQL_FastQuery
L 08/12/2016 - 05:56:40: [SM]   [1] Line 85, C:\Users\vBDSK\Desktop\scripting\elorank.sp::EloHandler()
L 08/12/2016 - 05:57:09: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 08/12/2016 - 05:57:09: [SM] Blaming: hlstatsx/elorank.smx()
L 08/12/2016 - 05:57:09: [SM] Call stack trace:
L 08/12/2016 - 05:57:09: [SM]   [0] SQL_FastQuery
L 08/12/2016 - 05:57:09: [SM]   [1] Line 85, C:\Users\vBDSK\Desktop\scripting\elorank.sp::EloHandler()

Can you help me?

**Comment by laam4** [comment]
Did you remember to modify the database.cfg? I'm not getting any errors :<

**Comment by vBDSK** [comment]
My mistake , I'm sorry

**Comment by laam4** [comment]
no problem :+1:
