### ISSUE TITLE
HLstatsX: CE

### ISSUE THREAD

**Issue by Dreizehnt** [laam4/noxus#22]
Hi, it I again :D At last established "noxus" (https://gmode.ru/hlstatsx/). Please help to adjust a line of activity ("Activity"), it just white and doesn't correspond to percent.

**Comment by hitmany** [comment]
Why this guy using Issues as forums? Its Github, not a Reddit.

**Comment by Dreizehnt** [comment]
This guy talks too. Where I can ask the author a question? What's wrong?

**Comment by laam4** [comment]
fix'd I guess?

**Comment by Dreizehnt** [comment]
Yes, thank you so much)
