### ISSUE TITLE
stuff missing on web/hlstatsimg/

### ISSUE THREAD

**Issue by TheSpartaPT** [laam4/noxus#6]
there are files missing there just sayin' ... ex.: bar1.gif to bar.6.gif, and also the progress folder and it's files.

you're wellcome :P

**Comment by TheSpartaPT** [comment]
might be more idk those are the most obvious ones

**Comment by laam4** [comment]
Nope, bar.gifs are missing because I removed them, because they were unnecessary after I changed stuff to use html <meter>. There could be some page which I didn't edit. Progress folder contains only automatically generated imagefiles, so I need to create a folder for you?

**Comment by TheSpartaPT** [comment]
The bar6.gif is still used at least on the player profile page i don't know where the others are used, and the progress folder is also used on the player profile page on the "Player Trend", so yeah :/

**Comment by TheSpartaPT** [comment]
also, where can i get the cs go heatmaps ?
